<?php
namespace App\Test\Fixture_deprecated;

use Cake\I18n\FrozenDate;
use Cake\TestSuite\Fixture\TestFixture;

/**
 * PeopleFixture
 *
 */
class PeopleFixture extends TestFixture {

	/**
	 * Import
	 *
	 * @var array
	 */
	public $import = ['table' => 'people'];

	/**
	 * Initialize function: Mostly, set up records
	 */
	public function init() {
		$this->records = [
			[
				'first_name' => 'Amy',
				'last_name' => 'Administrator',
				'publish_email' => true,
				'home_phone' => '(416) 234-5678',
				'publish_home_phone' => true,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '123 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(30),
				'height' => 66,
				'shirt_size' => 'Womens Small',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_ADMIN,
				'show_gravatar' => false,
				'alternate_first_name' => 'Buford',
				'alternate_last_name' => 'Tannen',
				'alternate_email' => 'Buford.Tannen@HillValley.com',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Mary',
				'last_name' => 'Manager',
				'publish_email' => true,
				'home_phone' => '(416) 345-6789',
				'publish_home_phone' => false,
				'work_phone' => '(416) 345-6790',
				'work_ext' => '123',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '234 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(29)->addMonths(1),
				'height' => 67,
				'shirt_size' => 'Womens Medium',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_MANAGER,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Cindy',
				'last_name' => 'Coordinator',
				'publish_email' => false,
				'home_phone' => '(416) 456-7890',
				'publish_home_phone' => true,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '345 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(28)->addMonths(2),
				'height' => 68,
				'shirt_size' => 'Womens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_COORDINATOR,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Crystal',
				'last_name' => 'Captain',
				'publish_email' => false,
				'home_phone' => '(416) 567-8910',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '456 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(27)->addMonths(3),
				'height' => 69,
				'shirt_size' => 'Womens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_CAPTAIN,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Chuck',
				'last_name' => 'Captain',
				'publish_email' => false,
				'home_phone' => '(416) 567-8910',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '456 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Man',
				'gender_description' => null,
				'roster_designation' => 'Open',
				'pronouns' => 'He, Him, His',
				'birthdate' => FrozenDate::now()->subYears(28)->addMonths(3),
				'height' => 70,
				'shirt_size' => 'Mens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_CAPTAIN2,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Carolyn',
				'last_name' => 'Captain',
				'publish_email' => false,
				'home_phone' => '(416) 987-6543',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '987 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(25)->addMonths(3),
				'height' => 70,
				'shirt_size' => 'Womens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_CAPTAIN3,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Carl',
				'last_name' => 'Captain',
				'publish_email' => false,
				'home_phone' => '(416) 765-4321',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '765 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Man',
				'gender_description' => null,
				'roster_designation' => 'Open',
				'pronouns' => 'He, Him, His',
				'birthdate' => FrozenDate::now()->subYears(28)->addMonths(8),
				'height' => 70,
				'shirt_size' => 'Mens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_CAPTAIN4,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Pam',
				'last_name' => 'Player',
				'publish_email' => false,
				'home_phone' => '(416) 678-9012',
				'publish_home_phone' => false,
				'work_phone' => '(416) 789-0123',
				'work_ext' => '456',
				'publish_work_phone' => false,
				'mobile_phone' => '',
				'publish_mobile_phone' => false,
				'addr_street' => '567 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(26)->addMonths(4),
				'height' => 70,
				'shirt_size' => 'Womens Large',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_PLAYER,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Carla',
				'last_name' => 'Child',
				'publish_email' => true,
				'publish_home_phone' => true,
				'publish_work_phone' => false,
				'publish_mobile_phone' => false,
				'addr_street' => '567 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(15),
				'height' => 62,
				'shirt_size' => 'Youth Medium',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => null,
				'show_gravatar' => false,
				'publish_alternate_email' => false,
				'publish_alternate_work_phone' => false,
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Mary',
				'last_name' => 'Duplicate',
				'publish_email' => false,
				'home_phone' => '(416) 345-6789',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '(416) 345-6790',
				'publish_mobile_phone' => false,
				'addr_street' => '236 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(29)->addMonths(1),
				'height' => 67,
				'shirt_size' => 'Womens Large',
				'status' => 'new',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_DUPLICATE,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Andy',
				'last_name' => 'Affiliate',
				'publish_email' => false,
				'home_phone' => '(647) 555-5555',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '(647) 555-5556',
				'publish_mobile_phone' => false,
				'addr_street' => '237 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Man',
				'gender_description' => null,
				'roster_designation' => 'Open',
				'pronouns' => 'He, Him, His',
				'birthdate' => FrozenDate::now()->subYears(30)->addMonths(1),
				'height' => 68,
				'shirt_size' => 'Mens Medium',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_ANDY_SUB,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Veronica',
				'last_name' => 'Visitor',
				'publish_email' => false,
				'home_phone' => '(647) 555-6666',
				'publish_home_phone' => false,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '(647) 555-6667',
				'publish_mobile_phone' => false,
				'addr_street' => '238 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(25),
				'height' => 68,
				'shirt_size' => 'Womens Medium',
				'status' => 'active',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_VISITOR,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
			[
				'first_name' => 'Irene',
				'last_name' => 'Inactive',
				'publish_email' => true,
				'home_phone' => '(647) 555-7777',
				'publish_home_phone' => true,
				'work_phone' => '',
				'work_ext' => '',
				'publish_work_phone' => false,
				'mobile_phone' => '(647) 555-7778',
				'publish_mobile_phone' => true,
				'addr_street' => '248 Main St.',
				'addr_city' => 'Toronto',
				'addr_prov' => 'Ontario',
				'addr_country' => 'Canada',
				'addr_postalcode' => 'M1A 1A1',
				'gender' => 'Woman',
				'gender_description' => null,
				'roster_designation' => 'Woman',
				'pronouns' => 'She, Her, Hers',
				'birthdate' => FrozenDate::now()->subYears(45),
				'height' => 68,
				'shirt_size' => 'Womens Medium',
				'status' => 'inactive',
				'has_dog' => false,
				'contact_for_feedback' => false,
				'complete' => true,
				'twitter_token' => '',
				'twitter_secret' => '',
				'user_id' => USER_ID_INACTIVE,
				'show_gravatar' => false,
				'alternate_first_name' => '',
				'alternate_last_name' => '',
				'alternate_email' => '',
				'publish_alternate_email' => false,
				'alternate_work_phone' => '',
				'alternate_work_ext' => '',
				'publish_alternate_work_phone' => false,
				'alternate_mobile_phone' => '',
				'publish_alternate_mobile_phone' => false,
				'modified' => FrozenDate::now(),
			],
		];

		if (!defined('PERSON_ID_ADMIN')) {
			$i = 0;
			define('PERSON_ID_ADMIN', ++$i);
			define('PERSON_ID_MANAGER', ++$i);
			define('PERSON_ID_COORDINATOR', ++$i);
			define('PERSON_ID_CAPTAIN', ++$i);
			define('PERSON_ID_CAPTAIN2', ++$i);
			define('PERSON_ID_CAPTAIN3', ++$i);
			define('PERSON_ID_CAPTAIN4', ++$i);
			define('PERSON_ID_PLAYER', ++$i);
			define('PERSON_ID_CHILD', ++$i);
			define('PERSON_ID_DUPLICATE', ++$i);
			define('PERSON_ID_ANDY_SUB', ++$i);
			define('PERSON_ID_VISITOR', ++$i);
			define('PERSON_ID_INACTIVE', ++$i);
			// *** Remember that when new People are added, the Users, AffiliatesPeople
			// GroupsPeople and Skills fixtures may also need to be updated ***
			// This must always be the last one in the list: it is for new
			// records created in UsersControllerTest
			define('PERSON_ID_NEW', ++$i);
		}

		parent::init();
	}

}
