<?php
use Migrations\AbstractSeed;

/**
 * Stat Types seed.
 */
class StatTypesSeed extends AbstractSeed {
	/**
	 * Run Method.
	 *
	 * @return void
	 */
	public function run() {
		$data = [
			/**
			 * Ultimate stats
			 */

			[
				'sport' => 'ultimate',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Goals per Game',
				'internal_name' => 'Goals per Game',
				'abbr' => 'GPG',
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Assists per Game',
				'internal_name' => 'Assists per Game',
				'abbr' => 'APG',
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Second Assists',
				'internal_name' => 'Second Assists',
				'abbr' => '2A',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Second Assists',
				'internal_name' => 'Second Assists',
				'abbr' => '2A',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Second Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Second Assists per Game',
				'internal_name' => 'Second Assists per Game',
				'abbr' => '2APG',
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Second Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Points per Game',
				'internal_name' => 'Points per Game',
				'abbr' => 'PPG',
				'sort' => 230,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'ultimate',
				'name' => 'D\'s',
				'internal_name' => 'D\'s',
				'abbr' => 'Ds',
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => 'D\'s',
				'internal_name' => 'D\'s',
				'abbr' => 'Ds',
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'D\'s',
			],

			[
				'sport' => 'ultimate',
				'name' => 'D\'s per Game',
				'internal_name' => 'D\'s per Game',
				'abbr' => 'DsPG',
				'sort' => 240,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'D\'s',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Throwaways',
				'internal_name' => 'Throwaways',
				'abbr' => 'TA',
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Throwaways',
				'internal_name' => 'Throwaways',
				'abbr' => 'TA',
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Throwaways',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Throwaways per Game',
				'internal_name' => 'Throwaways per Game',
				'abbr' => 'TAPG',
				'sort' => 250,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Throwaways',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Drops',
				'internal_name' => 'Drops',
				'abbr' => 'Dr',
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Drops',
				'internal_name' => 'Drops',
				'abbr' => 'Dr',
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Drops',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Drops per Game',
				'internal_name' => 'Drops per Game',
				'abbr' => 'DrPG',
				'sort' => 260,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Drops',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Turnovers per Game',
				'internal_name' => 'Turnovers per Game',
				'abbr' => 'TOPG',
				'sort' => 270,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => 'Salary',
				'internal_name' => 'Salary',
				'abbr' => '$',
				'sort' => 300,
				'class' => 'stat_season',
				'type' => 'season_calc',
				'handler' => 'salary',
			],

			/**
			 * Baseball stats
			 */

			[
				'sport' => 'baseball',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'baseball',
				'name' => 'At Bats',
				'internal_name' => 'At Bats',
				'abbr' => 'AB',
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'At Bats',
				'internal_name' => 'At Bats',
				'abbr' => 'AB',
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'At Bats',
			],

			[
				'sport' => 'baseball',
				'name' => 'Singles',
				'internal_name' => 'Singles',
				'abbr' => '1B',
				'sort' => 110,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Singles',
				'internal_name' => 'Singles',
				'abbr' => '1B',
				'sort' => 110,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Singles',
			],

			[
				'sport' => 'baseball',
				'name' => 'Doubles',
				'internal_name' => 'Doubles',
				'abbr' => '2B',
				'sort' => 120,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Doubles',
				'internal_name' => 'Doubles',
				'abbr' => '2B',
				'sort' => 120,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Doubles',
			],

			[
				'sport' => 'baseball',
				'name' => 'Triples',
				'internal_name' => 'Triples',
				'abbr' => '3B',
				'sort' => 130,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Triples',
				'internal_name' => 'Triples',
				'abbr' => '3B',
				'sort' => 130,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Triples',
			],

			[
				'sport' => 'baseball',
				'name' => 'Home Runs',
				'internal_name' => 'Home Runs',
				'abbr' => 'HR',
				'sort' => 140,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Home Runs',
				'internal_name' => 'Home Runs',
				'abbr' => 'HR',
				'sort' => 140,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Home Runs',
			],

			[
				'sport' => 'baseball',
				'name' => 'Hits',
				'internal_name' => 'Hits',
				'abbr' => 'H',
				'sort' => 150,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'hits',
			],

			[
				'sport' => 'baseball',
				'name' => 'Hits',
				'internal_name' => 'Hits',
				'abbr' => 'H',
				'sort' => 150,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Hits',
			],

			[
				'sport' => 'baseball',
				'name' => 'Walks',
				'internal_name' => 'Walks',
				'abbr' => 'BB',
				'sort' => 160,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Walks',
				'internal_name' => 'Walks',
				'abbr' => 'BB',
				'sort' => 160,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Walks',
			],

			[
				'sport' => 'baseball',
				'name' => 'Hit By Pitch',
				'internal_name' => 'Hit By Pitch',
				'abbr' => 'HBP',
				'sort' => 170,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Hit By Pitch',
				'internal_name' => 'Hit By Pitch',
				'abbr' => 'HBP',
				'sort' => 170,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Hit By Pitch',
			],

			[
				'sport' => 'baseball',
				'name' => 'Sacrifice Flies',
				'internal_name' => 'Sacrifice Flies',
				'abbr' => 'SF',
				'sort' => 180,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Sacrifice Flies',
				'internal_name' => 'Sacrifice Flies',
				'abbr' => 'SF',
				'sort' => 180,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Sacrifice Flies',
			],

			[
				'sport' => 'baseball',
				'name' => 'Strikeouts',
				'internal_name' => 'Strikeouts',
				'abbr' => 'K',
				'sort' => 190,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Strikeouts',
				'internal_name' => 'Strikeouts',
				'abbr' => 'K',
				'sort' => 190,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Strikeouts',
			],

			[
				'sport' => 'baseball',
				'name' => 'Runs Batted In',
				'internal_name' => 'Runs Batted In',
				'abbr' => 'RBI',
				'sort' => 200,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'baseball',
				'name' => 'Runs Batted In',
				'internal_name' => 'Runs Batted In',
				'abbr' => 'RBI',
				'sort' => 200,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Runs Batted In',
			],

			[
				'sport' => 'baseball',
				'name' => 'Runs Scored',
				'internal_name' => 'Runs Scored',
				'abbr' => 'R',
				'sort' => 210,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'baseball',
				'name' => 'Runs Scored',
				'internal_name' => 'Runs Scored',
				'abbr' => 'R',
				'sort' => 210,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Runs Scored',
			],

			[
				'sport' => 'baseball',
				'name' => 'Stolen Bases',
				'internal_name' => 'Stolen Bases',
				'abbr' => 'SB',
				'sort' => 220,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => 'Stolen Bases',
				'internal_name' => 'Stolen Bases',
				'abbr' => 'SB',
				'sort' => 220,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Stolen Bases',
			],

			[
				'sport' => 'baseball',
				'name' => 'Batting Average',
				'internal_name' => 'Batting Average',
				'abbr' => 'BA',
				'sort' => 300,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'ba',
			],

			[
				'sport' => 'baseball',
				'name' => 'On-base Percentage',
				'internal_name' => 'On-base Percentage',
				'abbr' => 'OBP',
				'sort' => 310,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'obp',
			],

			[
				'sport' => 'baseball',
				'name' => 'Slugging Average',
				'internal_name' => 'Slugging Average',
				'abbr' => 'SLG',
				'sort' => 320,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'slg',
			],

			[
				'sport' => 'baseball',
				'name' => 'On-base plus slugging',
				'internal_name' => 'On-base plus slugging',
				'abbr' => 'OPS',
				'sort' => 330,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'ops',
			],

			[
				'sport' => 'baseball',
				'positions' => '!designatedhitter',
				'name' => 'Errors',
				'internal_name' => 'Errors',
				'abbr' => 'E',
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => '!designatedhitter',
				'name' => 'Errors',
				'internal_name' => 'Errors',
				'abbr' => 'E',
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Errors',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 500,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 500,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 510,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 510,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 520,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 520,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Complete Games',
				'internal_name' => 'Complete Games',
				'abbr' => 'CG',
				'sort' => 530,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Complete Games',
				'internal_name' => 'Complete Games',
				'abbr' => 'CG',
				'sort' => 530,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Complete Games',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Innings Pitched',
				'internal_name' => 'Innings Pitched',
				'abbr' => 'IP',
				'sort' => 540,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'innings_sum',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Innings Pitched',
				'internal_name' => 'Innings Pitched',
				'abbr' => 'IP',
				'sort' => 540,
				'class' => 'stat_games',
				'type' => 'season_total',
				'handler' => 'innings',
				'base' => 'Innings Pitched',
				'sum_function' => 'innings_sum',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Hits',
				'internal_name' => 'Pitcher Hits',
				'abbr' => 'H',
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Hits',
				'internal_name' => 'Pitcher Hits',
				'abbr' => 'H',
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Hits',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Walks',
				'internal_name' => 'Pitcher Walks',
				'abbr' => 'BB',
				'sort' => 610,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Walks',
				'internal_name' => 'Pitcher Walks',
				'abbr' => 'BB',
				'sort' => 610,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Walks',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Strikeouts',
				'internal_name' => 'Pitcher Strikeouts',
				'abbr' => 'K',
				'sort' => 620,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Strikeouts',
				'internal_name' => 'Pitcher Strikeouts',
				'abbr' => 'K',
				'sort' => 620,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Strikeouts',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Earned Runs',
				'internal_name' => 'Earned Runs',
				'abbr' => 'ER',
				'sort' => 630,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'opponent_score',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => 'Earned Run Average',
				'internal_name' => 'Earned Run Average',
				'abbr' => 'ERA',
				'sort' => 640,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'era',
			],

			/**
			 * Basketball stats
			 */

			[
				'sport' => 'basketball',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'basketball',
				'name' => 'Started',
				'internal_name' => 'Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Games Started',
				'internal_name' => 'Games Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'basketball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'basketball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'basketball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 60,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'basketball',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'PTS',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'basketball',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'PTS',
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'basketball',
				'name' => 'Points per Game',
				'internal_name' => 'Points per Game',
				'abbr' => 'PPG',
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goals Made',
				'internal_name' => 'Field Goals Made',
				'abbr' => 'FGM',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goals Made',
				'internal_name' => 'Field Goals Made',
				'abbr' => 'FGM',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Field Goals Made',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goals Attempted',
				'internal_name' => 'Field Goals Attempted',
				'abbr' => 'FGA',
				'sort' => 111,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goals Attempted',
				'internal_name' => 'Field Goals Attempted',
				'abbr' => 'FGA',
				'sort' => 111,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Field Goals Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goal Percent',
				'internal_name' => 'Field Goal Percent',
				'abbr' => 'FG%',
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'fg_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Field Goal Percent',
				'internal_name' => 'Field Goal Percent',
				'abbr' => 'FG%',
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'fg_percent',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throws Made',
				'internal_name' => 'Free Throws Made',
				'abbr' => 'FGM',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throws Made',
				'internal_name' => 'Free Throws Made',
				'abbr' => 'FGM',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Free Throws Made',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throws Attempted',
				'internal_name' => 'Free Throws Attempted',
				'abbr' => 'FGA',
				'sort' => 121,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throws Attempted',
				'internal_name' => 'Free Throws Attempted',
				'abbr' => 'FGA',
				'sort' => 121,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Free Throws Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throw Percent',
				'internal_name' => 'Free Throw Percent',
				'abbr' => 'FT%',
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'ft_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Free Throw Percent',
				'internal_name' => 'Free Throw Percent',
				'abbr' => 'FT%',
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'ft_percent',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goals Made',
				'internal_name' => 'Three-point Field Goals Made',
				'abbr' => '3FGM',
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goals Made',
				'internal_name' => 'Three-point Field Goals Made',
				'abbr' => '3FGM',
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Three-point Field Goals Made',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goals Attempted',
				'internal_name' => 'Three-point Field Goals Attempted',
				'abbr' => '3FGA',
				'sort' => 131,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goals Attempted',
				'internal_name' => 'Three-point Field Goals Attempted',
				'abbr' => '3FGA',
				'sort' => 131,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Three-point Field Goals Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goal Percent',
				'internal_name' => 'Three-point Field Goal Percent',
				'abbr' => '3FG%',
				'sort' => 230,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'tpfg_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Three-point Field Goal Percent',
				'internal_name' => 'Three-point Field Goal Percent',
				'abbr' => '3FG%',
				'sort' => 230,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'tpfg_percent',
			],

			[
				'sport' => 'basketball',
				'name' => 'Offensive Rebounds',
				'internal_name' => 'Offensive Rebounds',
				'abbr' => 'OREB',
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Offensive Rebounds',
				'internal_name' => 'Offensive Rebounds',
				'abbr' => 'OREB',
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Offensive Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => 'Defensive Rebounds',
				'internal_name' => 'Defensive Rebounds',
				'abbr' => 'DREB',
				'sort' => 141,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Defensive Rebounds',
				'internal_name' => 'Defensive Rebounds',
				'abbr' => 'DREB',
				'sort' => 141,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Defensive Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => 'Rebounds',
				'internal_name' => 'Rebounds',
				'abbr' => 'REB',
				'sort' => 145,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => 'Rebounds',
				'internal_name' => 'Rebounds',
				'abbr' => 'REB',
				'sort' => 145,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => 'Rebounds per Game',
				'internal_name' => 'Rebounds per Game',
				'abbr' => 'RPG',
				'sort' => 245,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'AST',
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'AST',
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'basketball',
				'name' => 'Assists per Game',
				'internal_name' => 'Assists per Game',
				'abbr' => 'APG',
				'sort' => 250,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'basketball',
				'name' => 'Steals',
				'internal_name' => 'Steals',
				'abbr' => 'STL',
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Steals',
				'internal_name' => 'Steals',
				'abbr' => 'STL',
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Steals',
			],

			[
				'sport' => 'basketball',
				'name' => 'Steals per Game',
				'internal_name' => 'Steals per Game',
				'abbr' => 'SPG',
				'sort' => 260,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Steals',
			],

			[
				'sport' => 'basketball',
				'name' => 'Blocks',
				'internal_name' => 'Blocks',
				'abbr' => 'BLK',
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Blocks',
				'internal_name' => 'Blocks',
				'abbr' => 'BLK',
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Blocks',
			],

			[
				'sport' => 'basketball',
				'name' => 'Blocks per Game',
				'internal_name' => 'Blocks per Game',
				'abbr' => 'BPG',
				'sort' => 270,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Blocks',
			],

			[
				'sport' => 'basketball',
				'name' => 'Shots Rejected',
				'internal_name' => 'Shots Rejected',
				'abbr' => 'SR',
				'sort' => 180,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Shots Rejected',
				'internal_name' => 'Shots Rejected',
				'abbr' => 'SR',
				'sort' => 180,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots Rejected',
			],

			[
				'sport' => 'basketball',
				'name' => 'Shots Rejected per Game',
				'internal_name' => 'Shots Rejected per Game',
				'abbr' => 'SRPG',
				'sort' => 280,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Shots Rejected',
			],

			[
				'sport' => 'basketball',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'basketball',
				'name' => 'Turnovers per Game',
				'internal_name' => 'Turnovers per Game',
				'abbr' => 'TPG',
				'sort' => 290,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'basketball',
				'name' => 'Assist to Turnover Ratio',
				'internal_name' => 'Assist to Turnover Ratio',
				'abbr' => 'AST/TO',
				'sort' => 295,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'astto',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Assist to Turnover Ratio',
				'internal_name' => 'Assist to Turnover Ratio',
				'abbr' => 'AST/TO',
				'sort' => 295,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'astto',
			],

			[
				'sport' => 'basketball',
				'name' => 'Personal Fouls',
				'internal_name' => 'Personal Fouls',
				'abbr' => 'PF',
				'sort' => 300,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Personal Fouls',
				'internal_name' => 'Personal Fouls',
				'abbr' => 'PF',
				'sort' => 300,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Personal Fouls',
			],

			[
				'sport' => 'basketball',
				'name' => 'Personal Fouls per Game',
				'internal_name' => 'Personal Fouls per Game',
				'abbr' => 'PFPG',
				'sort' => 400,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Personal Fouls',
			],

			[
				'sport' => 'basketball',
				'name' => 'Fouls Drawn',
				'internal_name' => 'Fouls Drawn',
				'abbr' => 'FD',
				'sort' => 310,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => 'Fouls Drawn',
				'internal_name' => 'Fouls Drawn',
				'abbr' => 'PF',
				'sort' => 310,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Fouls Drawn',
			],

			[
				'sport' => 'basketball',
				'name' => 'Efficiency',
				'internal_name' => 'Efficiency',
				'abbr' => 'EFF',
				'sort' => 500,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'efficiency',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Efficiency',
				'internal_name' => 'Efficiency',
				'abbr' => 'EFF',
				'sort' => 500,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'efficiency',
			],

			[
				'sport' => 'basketball',
				'name' => 'Performance Index Rating',
				'internal_name' => 'Performance Index Rating',
				'abbr' => 'PIR',
				'sort' => 510,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'pir',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => 'Performance Index Rating',
				'internal_name' => 'Performance Index Rating',
				'abbr' => 'PIR',
				'sort' => 510,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'pir',
			],

			[
				'sport' => 'basketball',
				'name' => 'Minutes Played',
				'internal_name' => 'Minutes Played',
				'abbr' => 'MIN',
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'basketball',
				'name' => 'Minutes per Game',
				'internal_name' => 'Minutes per Game',
				'abbr' => 'MIN',
				'sort' => 600,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Minutes Played',
				'formatter_function' => 'minutes_format',
			],

			/**
			 * Cricket stats
			 */

			[
				'sport' => 'cricket',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'cricket',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'cricket',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'cricket',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'cricket',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],


			/**
			 * Dodgeball stats
			 */

			[
				'sport' => 'dodgeball',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Kills',
				'internal_name' => 'Kills',
				'abbr' => 'K+',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Kills',
				'internal_name' => 'Kills',
				'abbr' => 'K+',
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Kills',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Kills per Game',
				'internal_name' => 'Kills per Game',
				'abbr' => 'K+PG',
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Kills',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Killed',
				'internal_name' => 'Killed',
				'abbr' => 'K-',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Killed',
				'internal_name' => 'Killed',
				'abbr' => 'K-',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Killed',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Killed per Game',
				'internal_name' => 'Killed per Game',
				'abbr' => 'K-PG',
				'sort' => 210,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Killed',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Catches',
				'internal_name' => 'Catches',
				'abbr' => 'C+',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Catches',
				'internal_name' => 'Catches',
				'abbr' => 'C+',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Catches per Game',
				'internal_name' => 'Catches per Game',
				'abbr' => 'C+PG',
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Caught',
				'internal_name' => 'Caught',
				'abbr' => 'C-',
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Caught',
				'internal_name' => 'Caught',
				'abbr' => 'C-',
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Caught per Game',
				'internal_name' => 'Caught per Game',
				'abbr' => 'C-PG',
				'sort' => 230,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Caught',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'dodgeball',
				'name' => 'Points per Game',
				'internal_name' => 'Points per Game',
				'abbr' => 'PPG',
				'sort' => 290,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			/**
			 * Football stats
			 */

			[
				'sport' => 'football',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'football',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'football',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'football',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'football',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],


			/**
			 * Hockey stats
			 */

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Goals per Game',
				'internal_name' => 'Goals per Game',
				'abbr' => 'GPG',
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score_two',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Assists per Game',
				'internal_name' => 'Assists per Game',
				'abbr' => 'APG',
				'sort' => 210,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Points per Game',
				'internal_name' => 'Points per Game',
				'abbr' => 'PPG',
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Plus/Minus',
				'internal_name' => 'Plus Minus',
				'abbr' => '+/-',
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Plus/Minus',
				'internal_name' => 'Plus Minus',
				'abbr' => '+/-',
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Plus Minus',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Penalty Minutes',
				'internal_name' => 'Penalty Minutes',
				'abbr' => 'PIM',
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Penalty Minutes',
				'internal_name' => 'Penalty Minutes',
				'abbr' => 'PIM',
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalty Minutes',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Power Play Goals',
				'internal_name' => 'Power Play Goals',
				'abbr' => 'PPG',
				'sort' => 300,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Power Play Goals',
				'internal_name' => 'Power Play Goals',
				'abbr' => 'PPG',
				'sort' => 300,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Power Play Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shorthanded Goals',
				'internal_name' => 'Shorthanded Goals',
				'abbr' => 'SHG',
				'sort' => 310,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shorthanded Goals',
				'internal_name' => 'Shorthanded Goals',
				'abbr' => 'SHG',
				'sort' => 310,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shorthanded Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Game Winning Goals',
				'internal_name' => 'Game Winning Goals',
				'abbr' => 'GWG',
				'sort' => 320,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Game Winning Goals',
				'internal_name' => 'Game Winning Goals',
				'abbr' => 'GWG',
				'sort' => 320,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Game Winning Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shots',
				'internal_name' => 'Shots',
				'abbr' => 'S',
				'sort' => 330,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shots',
				'internal_name' => 'Shots',
				'abbr' => 'S',
				'sort' => 330,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shooting Percentage',
				'internal_name' => 'Shooting Percentage',
				'abbr' => 'S%',
				'sort' => 340,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'shot_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shooting Percentage',
				'internal_name' => 'Shooting Percentage',
				'abbr' => 'S%',
				'sort' => 340,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'shot_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shifts',
				'internal_name' => 'Shifts',
				'abbr' => 'SHIFTS',
				'sort' => 400,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Shifts',
				'internal_name' => 'Shifts',
				'abbr' => 'SHIFTS',
				'sort' => 400,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shifts',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Time On Ice',
				'internal_name' => 'Time On Ice',
				'abbr' => 'TOI',
				'sort' => 410,
				'class' => 'stat_game',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Time On Ice',
				'internal_name' => 'Time On Ice',
				'abbr' => 'TOI',
				'sort' => 410,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Time On Ice',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Time On Ice per Game',
				'internal_name' => 'Time On Ice per Game',
				'abbr' => 'TOIPG',
				'sort' => 510,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Time On Ice',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoffs',
				'internal_name' => 'Faceoffs',
				'abbr' => 'FO',
				'sort' => 600,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoffs',
				'internal_name' => 'Faceoffs',
				'abbr' => 'FO',
				'sort' => 600,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Faceoffs',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoffs Won',
				'internal_name' => 'Faceoffs Won',
				'abbr' => 'FOW',
				'sort' => 610,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoffs Won',
				'internal_name' => 'Faceoffs Won',
				'abbr' => 'FOW',
				'sort' => 610,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Faceoffs Won',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoff Percentage',
				'internal_name' => 'Faceoff Percentage',
				'abbr' => 'FO%',
				'sort' => 620,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'faceoff_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => 'Faceoff Percentage',
				'internal_name' => 'Faceoff Percentage',
				'abbr' => 'FO%',
				'sort' => 620,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'faceoff_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Hits',
				'internal_name' => 'Hits',
				'abbr' => 'H',
				'sort' => 700,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => 'Hits',
				'internal_name' => 'Hits',
				'abbr' => 'A',
				'sort' => 700,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Hits',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 1010,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 1010,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 1020,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 1020,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 1030,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 1030,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Overtime Losses',
				'internal_name' => 'Overtime Losses',
				'abbr' => 'OT',
				'sort' => 1040,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Overtime Losses',
				'internal_name' => 'Overtime Losses',
				'abbr' => 'OT',
				'sort' => 1040,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Overtime Losses',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shutouts',
				'internal_name' => 'Shutouts',
				'abbr' => 'SO',
				'sort' => 1050,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'shutouts',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shutouts',
				'internal_name' => 'Shutouts',
				'abbr' => 'SO',
				'sort' => 1050,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shutouts',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Goals Against Average',
				'internal_name' => 'Goals Against Average',
				'abbr' => 'GAA',
				'sort' => 1100,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'gaa',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Save Percentage',
				'internal_name' => 'Save Percentage',
				'abbr' => 'SV%',
				'sort' => 1110,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'save_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Save Percentage',
				'internal_name' => 'Save Percentage',
				'abbr' => 'SV%',
				'sort' => 1110,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'save_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Even Strength Goals Against',
				'internal_name' => 'Even Strength Goals Against',
				'abbr' => 'EV GA',
				'sort' => 1200,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Even Strength Goals Against',
				'internal_name' => 'Even Strength Goals Against',
				'abbr' => 'EV GA',
				'sort' => 1200,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Even Strength Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Power Play Goals Against',
				'internal_name' => 'Power Play Goals Against',
				'abbr' => 'PP GA',
				'sort' => 1210,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Power Play Goals Against',
				'internal_name' => 'Power Play Goals Against',
				'abbr' => 'PP GA',
				'sort' => 1210,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Power Play Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shorthanded Goals Against',
				'internal_name' => 'Shorthanded Goals Against',
				'abbr' => 'SH GA',
				'sort' => 1220,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shorthanded Goals Against',
				'internal_name' => 'Shorthanded Goals Against',
				'abbr' => 'SH GA',
				'sort' => 1220,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shorthanded Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Empty Net Goals Against',
				'internal_name' => 'Empty Net Goals Against',
				'abbr' => 'EN GA',
				'sort' => 1230,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Empty Net Goals Against',
				'internal_name' => 'Empty Net Goals Against',
				'abbr' => 'EN GA',
				'sort' => 1230,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Empty Net Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Goals Against',
				'internal_name' => 'Goals Against',
				'abbr' => 'GA',
				'sort' => 1240,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'goals_against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Goals Against',
				'internal_name' => 'Goals Against',
				'abbr' => 'GA',
				'sort' => 1240,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shots Against',
				'internal_name' => 'Shots Against',
				'abbr' => 'SA',
				'sort' => 1250,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Shots Against',
				'internal_name' => 'Shots Against',
				'abbr' => 'SA',
				'sort' => 1250,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shots Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Minutes Played',
				'internal_name' => 'Minutes Played',
				'abbr' => 'MIN',
				'sort' => 1300,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => 'Minutes Played',
				'internal_name' => 'Minutes Played',
				'abbr' => 'MIN',
				'sort' => 1300,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Minutes Played',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			/**
			 * Rugby stats
			 */

			[
				'sport' => 'rugby',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'rugby',
				'name' => 'Started',
				'internal_name' => 'Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Games Started',
				'internal_name' => 'Games Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'rugby',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'rugby',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => 'Draws',
				'internal_name' => 'Draws',
				'abbr' => 'D',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'rugby',
				'name' => 'Draws',
				'internal_name' => 'Draws',
				'abbr' => 'D',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Draws',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 60,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tries',
				'internal_name' => 'Tries',
				'abbr' => 'T',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tries',
				'internal_name' => 'Tries',
				'abbr' => 'T',
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Tries',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tries per Game',
				'internal_name' => 'Tries per Game',
				'abbr' => 'TPG',
				'sort' => 300,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Tries',
			],

			[
				'sport' => 'rugby',
				'name' => 'Conversions',
				'internal_name' => 'Conversions',
				'abbr' => 'C',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Conversions',
				'internal_name' => 'Conversions',
				'abbr' => 'C',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Conversions',
			],

			[
				'sport' => 'rugby',
				'name' => 'Conversions per Game',
				'internal_name' => 'Conversions per Game',
				'abbr' => 'CPG',
				'sort' => 310,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Conversions',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalty Kicks',
				'internal_name' => 'Penalty Kicks',
				'abbr' => 'PK',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalty Kicks',
				'internal_name' => 'Penalty Kicks',
				'abbr' => 'PK',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalty Kicks',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalty Kicks per Game',
				'internal_name' => 'Penalty Kicks per Game',
				'abbr' => 'PKPG',
				'sort' => 320,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalty Kicks',
			],

			[
				'sport' => 'rugby',
				'name' => 'Drop Goals',
				'internal_name' => 'Drop Goals',
				'abbr' => 'DG',
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Drop Goals',
				'internal_name' => 'Drop Goals',
				'abbr' => 'DG',
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Drop Goals',
			],

			[
				'sport' => 'rugby',
				'name' => 'Drop Goals per Game',
				'internal_name' => 'Drop Goals per Game',
				'abbr' => 'DGPG',
				'sort' => 330,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Drop Goals',
			],

			[
				'sport' => 'rugby',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'rugby',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'rugby',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'PPG',
				'sort' => 340,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'rugby',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'rugby',
				'name' => 'Assists per Game',
				'internal_name' => 'Assists per Game',
				'abbr' => 'APG',
				'sort' => 350,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'rugby',
				'name' => 'Interceptions',
				'internal_name' => 'Interceptions',
				'abbr' => 'I',
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Interceptions',
				'internal_name' => 'Interceptions',
				'abbr' => 'I',
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Interceptions',
			],

			[
				'sport' => 'rugby',
				'name' => 'Interceptions per Game',
				'internal_name' => 'Interceptions per Game',
				'abbr' => 'IPG',
				'sort' => 360,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Interceptions',
			],

			[
				'sport' => 'rugby',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Turnovers',
				'internal_name' => 'Turnovers',
				'abbr' => 'TO',
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'rugby',
				'name' => 'Turnovers per Game',
				'internal_name' => 'Turnovers per Game',
				'abbr' => 'TOPG',
				'sort' => 370,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tackles',
				'internal_name' => 'Tackles',
				'abbr' => 'Ta',
				'sort' => 180,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tackles',
				'internal_name' => 'Tackles',
				'abbr' => 'Ta',
				'sort' => 180,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => 'Tackles per Game',
				'internal_name' => 'Tackles per Game',
				'abbr' => 'TaPG',
				'sort' => 380,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => 'Missed Tackles',
				'internal_name' => 'Missed Tackles',
				'abbr' => 'MTa',
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Missed Tackles',
				'internal_name' => 'Missed Tackles',
				'abbr' => 'MTa',
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Missed Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => 'Missed Tackles per Game',
				'internal_name' => 'Missed Tackles per Game',
				'abbr' => 'MTaPG',
				'sort' => 390,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Missed Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Conceded',
				'internal_name' => 'Penalties Conceded',
				'abbr' => 'PC',
				'sort' => 200,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Conceded',
				'internal_name' => 'Penalties Conceded',
				'abbr' => 'PC',
				'sort' => 200,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalties Conceded',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Conceded per Game',
				'internal_name' => 'Penalties Conceded per Game',
				'abbr' => 'PCPG',
				'sort' => 400,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalties Conceded',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Won',
				'internal_name' => 'Penalties Won',
				'abbr' => 'PW',
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Won',
				'internal_name' => 'Penalties Won',
				'abbr' => 'PW',
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalties Won',
			],

			[
				'sport' => 'rugby',
				'name' => 'Penalties Won per Game',
				'internal_name' => 'Penalties Won per Game',
				'abbr' => 'PWPG',
				'sort' => 410,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalties Won',
			],

			[
				'sport' => 'rugby',
				'name' => 'Knock-ons',
				'internal_name' => 'Knock-ons',
				'abbr' => 'KO',
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => 'Knock-ons',
				'internal_name' => 'Knock-ons',
				'abbr' => 'KO',
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Knock-ons',
			],

			[
				'sport' => 'rugby',
				'name' => 'Knock-ons per Game',
				'internal_name' => 'Knock-ons per Game',
				'abbr' => 'KOPG',
				'sort' => 420,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Knock-ons',
			],

			/**
			 * Soccer stats
			 */

			[
				'sport' => 'soccer',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'soccer',
				'name' => 'Started',
				'internal_name' => 'Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => 'Games Started',
				'internal_name' => 'Games Started',
				'abbr' => 'GS',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'name' => 'Minutes Played',
				'internal_name' => 'Minutes Played',
				'abbr' => 'MIN',
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'soccer',
				'name' => 'Minutes Played',
				'internal_name' => 'Minutes Played',
				'abbr' => 'MIN',
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Minutes Played',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'soccer',
				'name' => 'Yellow Cards',
				'internal_name' => 'Yellow Cards',
				'abbr' => 'YC',
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => 'Yellow Cards',
				'internal_name' => 'Yellow Cards',
				'abbr' => 'YC',
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Yellow Cards',
			],

			[
				'sport' => 'soccer',
				'name' => 'Red Cards',
				'internal_name' => 'Red Cards',
				'abbr' => 'RC',
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => 'Red Cards',
				'internal_name' => 'Red Cards',
				'abbr' => 'RC',
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Red Cards',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 200,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Goals',
				'internal_name' => 'Goals',
				'abbr' => 'G',
				'sort' => 200,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Goals per Game',
				'internal_name' => 'Goals per Game',
				'abbr' => 'GPG',
				'sort' => 300,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score_two',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Assists',
				'internal_name' => 'Assists',
				'abbr' => 'A',
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Assists per Game',
				'internal_name' => 'Assists per Game',
				'abbr' => 'APG',
				'sort' => 310,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Points',
				'internal_name' => 'Points',
				'abbr' => 'P',
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Points per Game',
				'internal_name' => 'Points per Game',
				'abbr' => 'PPG',
				'sort' => 320,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Game Winning Goals',
				'internal_name' => 'Game Winning Goals',
				'abbr' => 'GWG',
				'sort' => 230,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Game Winning Goals',
				'internal_name' => 'Game Winning Goals',
				'abbr' => 'GWG',
				'sort' => 230,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Game Winning Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Shots',
				'internal_name' => 'Shots',
				'abbr' => 'S',
				'sort' => 240,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Shots',
				'internal_name' => 'Shots',
				'abbr' => 'S',
				'sort' => 240,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Shooting Percentage',
				'internal_name' => 'Shooting Percentage',
				'abbr' => 'S%',
				'sort' => 250,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'shot_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => 'Shooting Percentage',
				'internal_name' => 'Shooting Percentage',
				'abbr' => 'S%',
				'sort' => 250,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'shot_percent',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 410,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 410,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 420,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 420,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Shutouts',
				'internal_name' => 'Shutouts',
				'abbr' => 'SO',
				'sort' => 430,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Shutouts',
				'internal_name' => 'Shutouts',
				'abbr' => 'SO',
				'sort' => 430,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shutouts',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Goals Against',
				'internal_name' => 'Goals Against',
				'abbr' => 'GA',
				'sort' => 440,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'opponent_score',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Goals Against',
				'internal_name' => 'Goals Against',
				'abbr' => 'GA',
				'sort' => 440,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Goals Against',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Shots Against',
				'internal_name' => 'Shots Against',
				'abbr' => 'SA',
				'sort' => 450,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Shots Against',
				'internal_name' => 'Shots Against',
				'abbr' => 'SA',
				'sort' => 450,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shots Against',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Save Percentage',
				'internal_name' => 'Save Percentage',
				'abbr' => 'SV%',
				'sort' => 460,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'save_percent',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Save Percentage',
				'internal_name' => 'Save Percentage',
				'abbr' => 'SV%',
				'sort' => 460,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'save_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => 'Goals Against Average',
				'internal_name' => 'Goals Against Average',
				'abbr' => 'GAA',
				'sort' => 470,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'gaa',
			],

			/**
			 * Volleyball stats
			 */

			[
				'sport' => 'volleyball',
				'name' => 'Games Played',
				'internal_name' => 'Games Played',
				'abbr' => 'GP',
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Wins',
				'internal_name' => 'Wins',
				'abbr' => 'W',
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Losses',
				'internal_name' => 'Losses',
				'abbr' => 'L',
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Ties',
				'internal_name' => 'Ties',
				'abbr' => 'T',
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => 'Win Percent',
				'internal_name' => 'Win Percent',
				'abbr' => 'W%',
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],
		];

		$table = $this->table('stat_types');
		$table->insert($data)->save();
	}
}
