<?php
use Migrations\AbstractSeed;

/**
 * Stat Types seed.
 */
class StatTypesSeed extends AbstractSeed {
	/**
	 * Data Method.
	 *
	 * @return mixed
	 */
	public function data() {
		return [
			/**
			 * Ultimate stats
			 */

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Goals per Game'),
				'internal_name' => 'Goals per Game',
				'abbr' => __dx('seeds', 'stats', 'GPG'),
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Assists per Game'),
				'internal_name' => 'Assists per Game',
				'abbr' => __dx('seeds', 'stats', 'APG'),
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Second Assists'),
				'internal_name' => 'Second Assists',
				'abbr' => __dx('seeds', 'stats', '2A'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Second Assists'),
				'internal_name' => 'Second Assists',
				'abbr' => __dx('seeds', 'stats', '2A'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Second Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Second Assists per Game'),
				'internal_name' => 'Second Assists per Game',
				'abbr' => __dx('seeds', 'stats', '2APG'),
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Second Assists',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Points per Game'),
				'internal_name' => 'Points per Game',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 230,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'D\'s'),
				'internal_name' => 'D\'s',
				'abbr' => __dx('seeds', 'stats', 'Ds'),
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'D\'s'),
				'internal_name' => 'D\'s',
				'abbr' => __dx('seeds', 'stats', 'Ds'),
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'D\'s',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'D\'s per Game'),
				'internal_name' => 'D\'s per Game',
				'abbr' => __dx('seeds', 'stats', 'DsPG'),
				'sort' => 240,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'D\'s',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Throwaways'),
				'internal_name' => 'Throwaways',
				'abbr' => __dx('seeds', 'stats', 'TA'),
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Throwaways'),
				'internal_name' => 'Throwaways',
				'abbr' => __dx('seeds', 'stats', 'TA'),
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Throwaways',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Throwaways per Game'),
				'internal_name' => 'Throwaways per Game',
				'abbr' => __dx('seeds', 'stats', 'TAPG'),
				'sort' => 250,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Throwaways',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Drops'),
				'internal_name' => 'Drops',
				'abbr' => __dx('seeds', 'stats', 'Dr'),
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Drops'),
				'internal_name' => 'Drops',
				'abbr' => __dx('seeds', 'stats', 'Dr'),
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Drops',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Drops per Game'),
				'internal_name' => 'Drops per Game',
				'abbr' => __dx('seeds', 'stats', 'DrPG'),
				'sort' => 260,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Drops',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Turnovers per Game'),
				'internal_name' => 'Turnovers per Game',
				'abbr' => __dx('seeds', 'stats', 'TOPG'),
				'sort' => 270,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'ultimate',
				'name' => __d('seeds', 'Salary'),
				'internal_name' => 'Salary',
				'abbr' => __dx('seeds', 'stats', '$'),
				'sort' => 300,
				'class' => 'stat_season',
				'type' => 'season_calc',
				'handler' => 'salary',
			],

			/**
			 * Baseball stats
			 */

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'At Bats'),
				'internal_name' => 'At Bats',
				'abbr' => __dx('seeds', 'stats', 'AB'),
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'At Bats'),
				'internal_name' => 'At Bats',
				'abbr' => __dx('seeds', 'stats', 'AB'),
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'At Bats',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Singles'),
				'internal_name' => 'Singles',
				'abbr' => __dx('seeds', 'stats', '1B'),
				'sort' => 110,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Singles'),
				'internal_name' => 'Singles',
				'abbr' => __dx('seeds', 'stats', '1B'),
				'sort' => 110,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Singles',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Doubles'),
				'internal_name' => 'Doubles',
				'abbr' => __dx('seeds', 'stats', '2B'),
				'sort' => 120,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Doubles'),
				'internal_name' => 'Doubles',
				'abbr' => __dx('seeds', 'stats', '2B'),
				'sort' => 120,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Doubles',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Triples'),
				'internal_name' => 'Triples',
				'abbr' => __dx('seeds', 'stats', '3B'),
				'sort' => 130,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Triples'),
				'internal_name' => 'Triples',
				'abbr' => __dx('seeds', 'stats', '3B'),
				'sort' => 130,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Triples',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Home Runs'),
				'internal_name' => 'Home Runs',
				'abbr' => __dx('seeds', 'stats', 'HR'),
				'sort' => 140,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Home Runs'),
				'internal_name' => 'Home Runs',
				'abbr' => __dx('seeds', 'stats', 'HR'),
				'sort' => 140,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Home Runs',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Hits',
				'abbr' => __dx('seeds', 'stats', 'H'),
				'sort' => 150,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'hits',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Hits',
				'abbr' => __dx('seeds', 'stats', 'H'),
				'sort' => 150,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Hits',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Walks'),
				'internal_name' => 'Walks',
				'abbr' => __dx('seeds', 'stats', 'BB'),
				'sort' => 160,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Walks'),
				'internal_name' => 'Walks',
				'abbr' => __dx('seeds', 'stats', 'BB'),
				'sort' => 160,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Walks',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Hit By Pitch'),
				'internal_name' => 'Hit By Pitch',
				'abbr' => __dx('seeds', 'stats', 'HBP'),
				'sort' => 170,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Hit By Pitch'),
				'internal_name' => 'Hit By Pitch',
				'abbr' => __dx('seeds', 'stats', 'HBP'),
				'sort' => 170,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Hit By Pitch',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Sacrifice Flies'),
				'internal_name' => 'Sacrifice Flies',
				'abbr' => __dx('seeds', 'stats', 'SF'),
				'sort' => 180,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Sacrifice Flies'),
				'internal_name' => 'Sacrifice Flies',
				'abbr' => __dx('seeds', 'stats', 'SF'),
				'sort' => 180,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Sacrifice Flies',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Strikeouts'),
				'internal_name' => 'Strikeouts',
				'abbr' => __dx('seeds', 'stats', 'K'),
				'sort' => 190,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Strikeouts'),
				'internal_name' => 'Strikeouts',
				'abbr' => __dx('seeds', 'stats', 'K'),
				'sort' => 190,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Strikeouts',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Runs Batted In'),
				'internal_name' => 'Runs Batted In',
				'abbr' => __dx('seeds', 'stats', 'RBI'),
				'sort' => 200,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Runs Batted In'),
				'internal_name' => 'Runs Batted In',
				'abbr' => __dx('seeds', 'stats', 'RBI'),
				'sort' => 200,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Runs Batted In',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Runs Scored'),
				'internal_name' => 'Runs Scored',
				'abbr' => __dx('seeds', 'stats', 'R'),
				'sort' => 210,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Runs Scored'),
				'internal_name' => 'Runs Scored',
				'abbr' => __dx('seeds', 'stats', 'R'),
				'sort' => 210,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Runs Scored',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Stolen Bases'),
				'internal_name' => 'Stolen Bases',
				'abbr' => __dx('seeds', 'stats', 'SB'),
				'sort' => 220,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Stolen Bases'),
				'internal_name' => 'Stolen Bases',
				'abbr' => __dx('seeds', 'stats', 'SB'),
				'sort' => 220,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Stolen Bases',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Batting Average'),
				'internal_name' => 'Batting Average',
				'abbr' => __dx('seeds', 'stats', 'BA'),
				'sort' => 300,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'ba',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'On-base Percentage'),
				'internal_name' => 'On-base Percentage',
				'abbr' => __dx('seeds', 'stats', 'OBP'),
				'sort' => 310,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'obp',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'Slugging Average'),
				'internal_name' => 'Slugging Average',
				'abbr' => __dx('seeds', 'stats', 'SLG'),
				'sort' => 320,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'slg',
			],

			[
				'sport' => 'baseball',
				'name' => __d('seeds', 'On-base plus slugging'),
				'internal_name' => 'On-base plus slugging',
				'abbr' => __dx('seeds', 'stats', 'OPS'),
				'sort' => 330,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'ops',
			],

			[
				'sport' => 'baseball',
				'positions' => '!designatedhitter',
				'name' => __d('seeds', 'Errors'),
				'internal_name' => 'Errors',
				'abbr' => __dx('seeds', 'stats', 'E'),
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => '!designatedhitter',
				'name' => __d('seeds', 'Errors'),
				'internal_name' => 'Errors',
				'abbr' => __dx('seeds', 'stats', 'E'),
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Errors',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 500,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 500,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 510,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 510,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 520,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 520,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Complete Games'),
				'internal_name' => 'Complete Games',
				'abbr' => __dx('seeds', 'stats', 'CG'),
				'sort' => 530,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Complete Games'),
				'internal_name' => 'Complete Games',
				'abbr' => __dx('seeds', 'stats', 'CG'),
				'sort' => 530,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Complete Games',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Innings Pitched'),
				'internal_name' => 'Innings Pitched',
				'abbr' => __dx('seeds', 'stats', 'IP'),
				'sort' => 540,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'innings_sum',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Innings Pitched'),
				'internal_name' => 'Innings Pitched',
				'abbr' => __dx('seeds', 'stats', 'IP'),
				'sort' => 540,
				'class' => 'stat_games',
				'type' => 'season_total',
				'handler' => 'innings',
				'base' => 'Innings Pitched',
				'sum_function' => 'innings_sum',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Pitcher Hits',
				'abbr' => __dx('seeds', 'stats', 'H'),
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Pitcher Hits',
				'abbr' => __dx('seeds', 'stats', 'H'),
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Hits',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Walks'),
				'internal_name' => 'Pitcher Walks',
				'abbr' => __dx('seeds', 'stats', 'BB'),
				'sort' => 610,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Walks'),
				'internal_name' => 'Pitcher Walks',
				'abbr' => __dx('seeds', 'stats', 'BB'),
				'sort' => 610,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Walks',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Strikeouts'),
				'internal_name' => 'Pitcher Strikeouts',
				'abbr' => __dx('seeds', 'stats', 'K'),
				'sort' => 620,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Strikeouts'),
				'internal_name' => 'Pitcher Strikeouts',
				'abbr' => __dx('seeds', 'stats', 'K'),
				'sort' => 620,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Pitcher Strikeouts',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Earned Runs'),
				'internal_name' => 'Earned Runs',
				'abbr' => __dx('seeds', 'stats', 'ER'),
				'sort' => 630,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'opponent_score',
			],

			[
				'sport' => 'baseball',
				'positions' => 'pitcher',
				'name' => __d('seeds', 'Earned Run Average'),
				'internal_name' => 'Earned Run Average',
				'abbr' => __dx('seeds', 'stats', 'ERA'),
				'sort' => 640,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'era',
			],

			/**
			 * Basketball stats
			 */

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Started'),
				'internal_name' => 'Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Games Started'),
				'internal_name' => 'Games Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 60,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'PTS'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'PTS'),
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Points per Game'),
				'internal_name' => 'Points per Game',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goals Made'),
				'internal_name' => 'Field Goals Made',
				'abbr' => __dx('seeds', 'stats', 'FGM'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goals Made'),
				'internal_name' => 'Field Goals Made',
				'abbr' => __dx('seeds', 'stats', 'FGM'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Field Goals Made',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goals Attempted'),
				'internal_name' => 'Field Goals Attempted',
				'abbr' => __dx('seeds', 'stats', 'FGA'),
				'sort' => 111,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goals Attempted'),
				'internal_name' => 'Field Goals Attempted',
				'abbr' => __dx('seeds', 'stats', 'FGA'),
				'sort' => 111,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Field Goals Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goal Percent'),
				'internal_name' => 'Field Goal Percent',
				'abbr' => __dx('seeds', 'stats', 'FG%'),
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'fg_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Field Goal Percent'),
				'internal_name' => 'Field Goal Percent',
				'abbr' => __dx('seeds', 'stats', 'FG%'),
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'fg_percent',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throws Made'),
				'internal_name' => 'Free Throws Made',
				'abbr' => __dx('seeds', 'stats', 'FGM'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throws Made'),
				'internal_name' => 'Free Throws Made',
				'abbr' => __dx('seeds', 'stats', 'FGM'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Free Throws Made',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throws Attempted'),
				'internal_name' => 'Free Throws Attempted',
				'abbr' => __dx('seeds', 'stats', 'FGA'),
				'sort' => 121,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throws Attempted'),
				'internal_name' => 'Free Throws Attempted',
				'abbr' => __dx('seeds', 'stats', 'FGA'),
				'sort' => 121,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Free Throws Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throw Percent'),
				'internal_name' => 'Free Throw Percent',
				'abbr' => __dx('seeds', 'stats', 'FT%'),
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'ft_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Free Throw Percent'),
				'internal_name' => 'Free Throw Percent',
				'abbr' => __dx('seeds', 'stats', 'FT%'),
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'ft_percent',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goals Made'),
				'internal_name' => 'Three-point Field Goals Made',
				'abbr' => __dx('seeds', 'stats', '3FGM'),
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goals Made'),
				'internal_name' => 'Three-point Field Goals Made',
				'abbr' => __dx('seeds', 'stats', '3FGM'),
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Three-point Field Goals Made',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goals Attempted'),
				'internal_name' => 'Three-point Field Goals Attempted',
				'abbr' => __dx('seeds', 'stats', '3FGA'),
				'sort' => 131,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goals Attempted'),
				'internal_name' => 'Three-point Field Goals Attempted',
				'abbr' => __dx('seeds', 'stats', '3FGA'),
				'sort' => 131,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Three-point Field Goals Attempted',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goal Percent'),
				'internal_name' => 'Three-point Field Goal Percent',
				'abbr' => __dx('seeds', 'stats', '3FG%'),
				'sort' => 230,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'tpfg_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Three-point Field Goal Percent'),
				'internal_name' => 'Three-point Field Goal Percent',
				'abbr' => __dx('seeds', 'stats', '3FG%'),
				'sort' => 230,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'tpfg_percent',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Offensive Rebounds'),
				'internal_name' => 'Offensive Rebounds',
				'abbr' => __dx('seeds', 'stats', 'OREB'),
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Offensive Rebounds'),
				'internal_name' => 'Offensive Rebounds',
				'abbr' => __dx('seeds', 'stats', 'OREB'),
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Offensive Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Defensive Rebounds'),
				'internal_name' => 'Defensive Rebounds',
				'abbr' => __dx('seeds', 'stats', 'DREB'),
				'sort' => 141,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Defensive Rebounds'),
				'internal_name' => 'Defensive Rebounds',
				'abbr' => __dx('seeds', 'stats', 'DREB'),
				'sort' => 141,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Defensive Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Rebounds'),
				'internal_name' => 'Rebounds',
				'abbr' => __dx('seeds', 'stats', 'REB'),
				'sort' => 145,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Rebounds'),
				'internal_name' => 'Rebounds',
				'abbr' => __dx('seeds', 'stats', 'REB'),
				'sort' => 145,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Rebounds per Game'),
				'internal_name' => 'Rebounds per Game',
				'abbr' => __dx('seeds', 'stats', 'RPG'),
				'sort' => 245,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Rebounds',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'AST'),
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'AST'),
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Assists per Game'),
				'internal_name' => 'Assists per Game',
				'abbr' => __dx('seeds', 'stats', 'APG'),
				'sort' => 250,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Steals'),
				'internal_name' => 'Steals',
				'abbr' => __dx('seeds', 'stats', 'STL'),
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Steals'),
				'internal_name' => 'Steals',
				'abbr' => __dx('seeds', 'stats', 'STL'),
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Steals',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Steals per Game'),
				'internal_name' => 'Steals per Game',
				'abbr' => __dx('seeds', 'stats', 'SPG'),
				'sort' => 260,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Steals',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Blocks'),
				'internal_name' => 'Blocks',
				'abbr' => __dx('seeds', 'stats', 'BLK'),
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Blocks'),
				'internal_name' => 'Blocks',
				'abbr' => __dx('seeds', 'stats', 'BLK'),
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Blocks',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Blocks per Game'),
				'internal_name' => 'Blocks per Game',
				'abbr' => __dx('seeds', 'stats', 'BPG'),
				'sort' => 270,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Blocks',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Shots Rejected'),
				'internal_name' => 'Shots Rejected',
				'abbr' => __dx('seeds', 'stats', 'SR'),
				'sort' => 180,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Shots Rejected'),
				'internal_name' => 'Shots Rejected',
				'abbr' => __dx('seeds', 'stats', 'SR'),
				'sort' => 180,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots Rejected',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Shots Rejected per Game'),
				'internal_name' => 'Shots Rejected per Game',
				'abbr' => __dx('seeds', 'stats', 'SRPG'),
				'sort' => 280,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Shots Rejected',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Turnovers per Game'),
				'internal_name' => 'Turnovers per Game',
				'abbr' => __dx('seeds', 'stats', 'TPG'),
				'sort' => 290,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Assist to Turnover Ratio'),
				'internal_name' => 'Assist to Turnover Ratio',
				'abbr' => __dx('seeds', 'stats', 'AST/TO'),
				'sort' => 295,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'astto',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Assist to Turnover Ratio'),
				'internal_name' => 'Assist to Turnover Ratio',
				'abbr' => __dx('seeds', 'stats', 'AST/TO'),
				'sort' => 295,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'astto',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Personal Fouls'),
				'internal_name' => 'Personal Fouls',
				'abbr' => __dx('seeds', 'stats', 'PF'),
				'sort' => 300,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Personal Fouls'),
				'internal_name' => 'Personal Fouls',
				'abbr' => __dx('seeds', 'stats', 'PF'),
				'sort' => 300,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Personal Fouls',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Personal Fouls per Game'),
				'internal_name' => 'Personal Fouls per Game',
				'abbr' => __dx('seeds', 'stats', 'PFPG'),
				'sort' => 400,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Personal Fouls',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Fouls Drawn'),
				'internal_name' => 'Fouls Drawn',
				'abbr' => __dx('seeds', 'stats', 'FD'),
				'sort' => 310,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Fouls Drawn'),
				'internal_name' => 'Fouls Drawn',
				'abbr' => __dx('seeds', 'stats', 'PF'),
				'sort' => 310,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Fouls Drawn',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Efficiency'),
				'internal_name' => 'Efficiency',
				'abbr' => __dx('seeds', 'stats', 'EFF'),
				'sort' => 500,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'efficiency',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Efficiency'),
				'internal_name' => 'Efficiency',
				'abbr' => __dx('seeds', 'stats', 'EFF'),
				'sort' => 500,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'efficiency',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Performance Index Rating'),
				'internal_name' => 'Performance Index Rating',
				'abbr' => __dx('seeds', 'stats', 'PIR'),
				'sort' => 510,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'pir',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Performance Index Rating'),
				'internal_name' => 'Performance Index Rating',
				'abbr' => __dx('seeds', 'stats', 'PIR'),
				'sort' => 510,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'pir',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Minutes Played'),
				'internal_name' => 'Minutes Played',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 600,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'basketball',
				'name' => __d('seeds', 'Minutes per Game'),
				'internal_name' => 'Minutes per Game',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 600,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Minutes Played',
				'formatter_function' => 'minutes_format',
			],

			/**
			 * Cricket stats
			 */

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'cricket',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],


			/**
			 * Dodgeball stats
			 */

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Kills'),
				'internal_name' => 'Kills',
				'abbr' => __dx('seeds', 'stats', 'K+'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Kills'),
				'internal_name' => 'Kills',
				'abbr' => __dx('seeds', 'stats', 'K+'),
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Kills',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Kills per Game'),
				'internal_name' => 'Kills per Game',
				'abbr' => __dx('seeds', 'stats', 'K+PG'),
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Kills',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Killed'),
				'internal_name' => 'Killed',
				'abbr' => __dx('seeds', 'stats', 'K-'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Killed'),
				'internal_name' => 'Killed',
				'abbr' => __dx('seeds', 'stats', 'K-'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Killed',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Killed per Game'),
				'internal_name' => 'Killed per Game',
				'abbr' => __dx('seeds', 'stats', 'K-PG'),
				'sort' => 210,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Killed',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Catches'),
				'internal_name' => 'Catches',
				'abbr' => __dx('seeds', 'stats', 'C+'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Catches'),
				'internal_name' => 'Catches',
				'abbr' => __dx('seeds', 'stats', 'C+'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Catches per Game'),
				'internal_name' => 'Catches per Game',
				'abbr' => __dx('seeds', 'stats', 'C+PG'),
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Caught'),
				'internal_name' => 'Caught',
				'abbr' => __dx('seeds', 'stats', 'C-'),
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Caught'),
				'internal_name' => 'Caught',
				'abbr' => __dx('seeds', 'stats', 'C-'),
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Catches',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Caught per Game'),
				'internal_name' => 'Caught per Game',
				'abbr' => __dx('seeds', 'stats', 'C-PG'),
				'sort' => 230,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Caught',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'dodgeball',
				'name' => __d('seeds', 'Points per Game'),
				'internal_name' => 'Points per Game',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 290,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			/**
			 * Football stats
			 */

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'football',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],


			/**
			 * Hockey stats
			 */

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Goals per Game'),
				'internal_name' => 'Goals per Game',
				'abbr' => __dx('seeds', 'stats', 'GPG'),
				'sort' => 200,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score_two',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Assists per Game'),
				'internal_name' => 'Assists per Game',
				'abbr' => __dx('seeds', 'stats', 'APG'),
				'sort' => 210,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Points per Game'),
				'internal_name' => 'Points per Game',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 220,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Plus/Minus'),
				'internal_name' => 'Plus Minus',
				'abbr' => __dx('seeds', 'stats', '+/-'),
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Plus/Minus'),
				'internal_name' => 'Plus Minus',
				'abbr' => __dx('seeds', 'stats', '+/-'),
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Plus Minus',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Penalty Minutes'),
				'internal_name' => 'Penalty Minutes',
				'abbr' => __dx('seeds', 'stats', 'PIM'),
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Penalty Minutes'),
				'internal_name' => 'Penalty Minutes',
				'abbr' => __dx('seeds', 'stats', 'PIM'),
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalty Minutes',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Power Play Goals'),
				'internal_name' => 'Power Play Goals',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 300,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Power Play Goals'),
				'internal_name' => 'Power Play Goals',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 300,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Power Play Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shorthanded Goals'),
				'internal_name' => 'Shorthanded Goals',
				'abbr' => __dx('seeds', 'stats', 'SHG'),
				'sort' => 310,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shorthanded Goals'),
				'internal_name' => 'Shorthanded Goals',
				'abbr' => __dx('seeds', 'stats', 'SHG'),
				'sort' => 310,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shorthanded Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Game Winning Goals'),
				'internal_name' => 'Game Winning Goals',
				'abbr' => __dx('seeds', 'stats', 'GWG'),
				'sort' => 320,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Game Winning Goals'),
				'internal_name' => 'Game Winning Goals',
				'abbr' => __dx('seeds', 'stats', 'GWG'),
				'sort' => 320,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Game Winning Goals',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shots'),
				'internal_name' => 'Shots',
				'abbr' => __dx('seeds', 'stats', 'S'),
				'sort' => 330,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shots'),
				'internal_name' => 'Shots',
				'abbr' => __dx('seeds', 'stats', 'S'),
				'sort' => 330,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shooting Percentage'),
				'internal_name' => 'Shooting Percentage',
				'abbr' => __dx('seeds', 'stats', 'S%'),
				'sort' => 340,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'shot_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shooting Percentage'),
				'internal_name' => 'Shooting Percentage',
				'abbr' => __dx('seeds', 'stats', 'S%'),
				'sort' => 340,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'shot_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shifts'),
				'internal_name' => 'Shifts',
				'abbr' => __dx('seeds', 'stats', 'SHIFTS'),
				'sort' => 400,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Shifts'),
				'internal_name' => 'Shifts',
				'abbr' => __dx('seeds', 'stats', 'SHIFTS'),
				'sort' => 400,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shifts',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Time On Ice'),
				'internal_name' => 'Time On Ice',
				'abbr' => __dx('seeds', 'stats', 'TOI'),
				'sort' => 410,
				'class' => 'stat_game',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Time On Ice'),
				'internal_name' => 'Time On Ice',
				'abbr' => __dx('seeds', 'stats', 'TOI'),
				'sort' => 410,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Time On Ice',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Time On Ice per Game'),
				'internal_name' => 'Time On Ice per Game',
				'abbr' => __dx('seeds', 'stats', 'TOIPG'),
				'sort' => 510,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Time On Ice',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoffs'),
				'internal_name' => 'Faceoffs',
				'abbr' => __dx('seeds', 'stats', 'FO'),
				'sort' => 600,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoffs'),
				'internal_name' => 'Faceoffs',
				'abbr' => __dx('seeds', 'stats', 'FO'),
				'sort' => 600,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Faceoffs',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoffs Won'),
				'internal_name' => 'Faceoffs Won',
				'abbr' => __dx('seeds', 'stats', 'FOW'),
				'sort' => 610,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoffs Won'),
				'internal_name' => 'Faceoffs Won',
				'abbr' => __dx('seeds', 'stats', 'FOW'),
				'sort' => 610,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Faceoffs Won',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoff Percentage'),
				'internal_name' => 'Faceoff Percentage',
				'abbr' => __dx('seeds', 'stats', 'FO%'),
				'sort' => 620,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'faceoff_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie,!defence',
				'name' => __d('seeds', 'Faceoff Percentage'),
				'internal_name' => 'Faceoff Percentage',
				'abbr' => __dx('seeds', 'stats', 'FO%'),
				'sort' => 620,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'faceoff_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Hits',
				'abbr' => __dx('seeds', 'stats', 'H'),
				'sort' => 700,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => '!goalie',
				'name' => __d('seeds', 'Hits'),
				'internal_name' => 'Hits',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 700,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Hits',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 1010,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 1010,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 1020,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 1020,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 1030,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 1030,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Overtime Losses'),
				'internal_name' => 'Overtime Losses',
				'abbr' => __dx('seeds', 'stats', 'OT'),
				'sort' => 1040,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Overtime Losses'),
				'internal_name' => 'Overtime Losses',
				'abbr' => __dx('seeds', 'stats', 'OT'),
				'sort' => 1040,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Overtime Losses',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shutouts'),
				'internal_name' => 'Shutouts',
				'abbr' => __dx('seeds', 'stats', 'SO'),
				'sort' => 1050,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'shutouts',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shutouts'),
				'internal_name' => 'Shutouts',
				'abbr' => __dx('seeds', 'stats', 'SO'),
				'sort' => 1050,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shutouts',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Goals Against Average'),
				'internal_name' => 'Goals Against Average',
				'abbr' => __dx('seeds', 'stats', 'GAA'),
				'sort' => 1100,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'gaa',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Save Percentage'),
				'internal_name' => 'Save Percentage',
				'abbr' => __dx('seeds', 'stats', 'SV%'),
				'sort' => 1110,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'save_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Save Percentage'),
				'internal_name' => 'Save Percentage',
				'abbr' => __dx('seeds', 'stats', 'SV%'),
				'sort' => 1110,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'save_percent',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Even Strength Goals Against'),
				'internal_name' => 'Even Strength Goals Against',
				'abbr' => __dx('seeds', 'stats', 'EV GA'),
				'sort' => 1200,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Even Strength Goals Against'),
				'internal_name' => 'Even Strength Goals Against',
				'abbr' => __dx('seeds', 'stats', 'EV GA'),
				'sort' => 1200,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Even Strength Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Power Play Goals Against'),
				'internal_name' => 'Power Play Goals Against',
				'abbr' => __dx('seeds', 'stats', 'PP GA'),
				'sort' => 1210,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Power Play Goals Against'),
				'internal_name' => 'Power Play Goals Against',
				'abbr' => __dx('seeds', 'stats', 'PP GA'),
				'sort' => 1210,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Power Play Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shorthanded Goals Against'),
				'internal_name' => 'Shorthanded Goals Against',
				'abbr' => __dx('seeds', 'stats', 'SH GA'),
				'sort' => 1220,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shorthanded Goals Against'),
				'internal_name' => 'Shorthanded Goals Against',
				'abbr' => __dx('seeds', 'stats', 'SH GA'),
				'sort' => 1220,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shorthanded Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Empty Net Goals Against'),
				'internal_name' => 'Empty Net Goals Against',
				'abbr' => __dx('seeds', 'stats', 'EN GA'),
				'sort' => 1230,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Empty Net Goals Against'),
				'internal_name' => 'Empty Net Goals Against',
				'abbr' => __dx('seeds', 'stats', 'EN GA'),
				'sort' => 1230,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Empty Net Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Goals Against'),
				'internal_name' => 'Goals Against',
				'abbr' => __dx('seeds', 'stats', 'GA'),
				'sort' => 1240,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'goals_against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Goals Against'),
				'internal_name' => 'Goals Against',
				'abbr' => __dx('seeds', 'stats', 'GA'),
				'sort' => 1240,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Goals Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shots Against'),
				'internal_name' => 'Shots Against',
				'abbr' => __dx('seeds', 'stats', 'SA'),
				'sort' => 1250,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Shots Against'),
				'internal_name' => 'Shots Against',
				'abbr' => __dx('seeds', 'stats', 'SA'),
				'sort' => 1250,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shots Against',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Minutes Played'),
				'internal_name' => 'Minutes Played',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 1300,
				'class' => 'stat_games',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'hockey',
				'positions' => 'goalie',
				'name' => __d('seeds', 'Minutes Played'),
				'internal_name' => 'Minutes Played',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 1300,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Minutes Played',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			/**
			 * Rugby stats
			 */

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Started'),
				'internal_name' => 'Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Games Started'),
				'internal_name' => 'Games Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Draws'),
				'internal_name' => 'Draws',
				'abbr' => __dx('seeds', 'stats', 'D'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Draws'),
				'internal_name' => 'Draws',
				'abbr' => __dx('seeds', 'stats', 'D'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Draws',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 60,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tries'),
				'internal_name' => 'Tries',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tries'),
				'internal_name' => 'Tries',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 100,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Tries',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tries per Game'),
				'internal_name' => 'Tries per Game',
				'abbr' => __dx('seeds', 'stats', 'TPG'),
				'sort' => 300,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Tries',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Conversions'),
				'internal_name' => 'Conversions',
				'abbr' => __dx('seeds', 'stats', 'C'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Conversions'),
				'internal_name' => 'Conversions',
				'abbr' => __dx('seeds', 'stats', 'C'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Conversions',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Conversions per Game'),
				'internal_name' => 'Conversions per Game',
				'abbr' => __dx('seeds', 'stats', 'CPG'),
				'sort' => 310,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Conversions',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalty Kicks'),
				'internal_name' => 'Penalty Kicks',
				'abbr' => __dx('seeds', 'stats', 'PK'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalty Kicks'),
				'internal_name' => 'Penalty Kicks',
				'abbr' => __dx('seeds', 'stats', 'PK'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalty Kicks',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalty Kicks per Game'),
				'internal_name' => 'Penalty Kicks per Game',
				'abbr' => __dx('seeds', 'stats', 'PKPG'),
				'sort' => 320,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalty Kicks',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Drop Goals'),
				'internal_name' => 'Drop Goals',
				'abbr' => __dx('seeds', 'stats', 'DG'),
				'sort' => 130,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Drop Goals'),
				'internal_name' => 'Drop Goals',
				'abbr' => __dx('seeds', 'stats', 'DG'),
				'sort' => 130,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Drop Goals',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Drop Goals per Game'),
				'internal_name' => 'Drop Goals per Game',
				'abbr' => __dx('seeds', 'stats', 'DGPG'),
				'sort' => 330,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Drop Goals',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 140,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 140,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 340,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 150,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 150,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Assists per Game'),
				'internal_name' => 'Assists per Game',
				'abbr' => __dx('seeds', 'stats', 'APG'),
				'sort' => 350,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Interceptions'),
				'internal_name' => 'Interceptions',
				'abbr' => __dx('seeds', 'stats', 'I'),
				'sort' => 160,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Interceptions'),
				'internal_name' => 'Interceptions',
				'abbr' => __dx('seeds', 'stats', 'I'),
				'sort' => 160,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Interceptions',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Interceptions per Game'),
				'internal_name' => 'Interceptions per Game',
				'abbr' => __dx('seeds', 'stats', 'IPG'),
				'sort' => 360,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Interceptions',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 170,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Turnovers'),
				'internal_name' => 'Turnovers',
				'abbr' => __dx('seeds', 'stats', 'TO'),
				'sort' => 170,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Turnovers per Game'),
				'internal_name' => 'Turnovers per Game',
				'abbr' => __dx('seeds', 'stats', 'TOPG'),
				'sort' => 370,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Turnovers',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tackles'),
				'internal_name' => 'Tackles',
				'abbr' => __dx('seeds', 'stats', 'Ta'),
				'sort' => 180,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tackles'),
				'internal_name' => 'Tackles',
				'abbr' => __dx('seeds', 'stats', 'Ta'),
				'sort' => 180,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Tackles per Game'),
				'internal_name' => 'Tackles per Game',
				'abbr' => __dx('seeds', 'stats', 'TaPG'),
				'sort' => 380,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Missed Tackles'),
				'internal_name' => 'Missed Tackles',
				'abbr' => __dx('seeds', 'stats', 'MTa'),
				'sort' => 190,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Missed Tackles'),
				'internal_name' => 'Missed Tackles',
				'abbr' => __dx('seeds', 'stats', 'MTa'),
				'sort' => 190,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Missed Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Missed Tackles per Game'),
				'internal_name' => 'Missed Tackles per Game',
				'abbr' => __dx('seeds', 'stats', 'MTaPG'),
				'sort' => 390,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Missed Tackles',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Conceded'),
				'internal_name' => 'Penalties Conceded',
				'abbr' => __dx('seeds', 'stats', 'PC'),
				'sort' => 200,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Conceded'),
				'internal_name' => 'Penalties Conceded',
				'abbr' => __dx('seeds', 'stats', 'PC'),
				'sort' => 200,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalties Conceded',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Conceded per Game'),
				'internal_name' => 'Penalties Conceded per Game',
				'abbr' => __dx('seeds', 'stats', 'PCPG'),
				'sort' => 400,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalties Conceded',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Won'),
				'internal_name' => 'Penalties Won',
				'abbr' => __dx('seeds', 'stats', 'PW'),
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Won'),
				'internal_name' => 'Penalties Won',
				'abbr' => __dx('seeds', 'stats', 'PW'),
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Penalties Won',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Penalties Won per Game'),
				'internal_name' => 'Penalties Won per Game',
				'abbr' => __dx('seeds', 'stats', 'PWPG'),
				'sort' => 410,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Penalties Won',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Knock-ons'),
				'internal_name' => 'Knock-ons',
				'abbr' => __dx('seeds', 'stats', 'KO'),
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Knock-ons'),
				'internal_name' => 'Knock-ons',
				'abbr' => __dx('seeds', 'stats', 'KO'),
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Knock-ons',
			],

			[
				'sport' => 'rugby',
				'name' => __d('seeds', 'Knock-ons per Game'),
				'internal_name' => 'Knock-ons per Game',
				'abbr' => __dx('seeds', 'stats', 'KOPG'),
				'sort' => 420,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Knock-ons',
			],

			/**
			 * Soccer stats
			 */

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Started'),
				'internal_name' => 'Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Games Started'),
				'internal_name' => 'Games Started',
				'abbr' => __dx('seeds', 'stats', 'GS'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Started',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Minutes Played'),
				'internal_name' => 'Minutes Played',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 100,
				'class' => 'stat_game',
				'type' => 'entered',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Minutes Played'),
				'internal_name' => 'Minutes Played',
				'abbr' => __dx('seeds', 'stats', 'MIN'),
				'sort' => 100,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Minutes Played',
				'sum_function' => 'minutes_sum',
				'formatter_function' => 'minutes_format',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Yellow Cards'),
				'internal_name' => 'Yellow Cards',
				'abbr' => __dx('seeds', 'stats', 'YC'),
				'sort' => 110,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Yellow Cards'),
				'internal_name' => 'Yellow Cards',
				'abbr' => __dx('seeds', 'stats', 'YC'),
				'sort' => 110,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Yellow Cards',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Red Cards'),
				'internal_name' => 'Red Cards',
				'abbr' => __dx('seeds', 'stats', 'RC'),
				'sort' => 120,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'name' => __d('seeds', 'Red Cards'),
				'internal_name' => 'Red Cards',
				'abbr' => __dx('seeds', 'stats', 'RC'),
				'sort' => 120,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Red Cards',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 200,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Goals'),
				'internal_name' => 'Goals',
				'abbr' => __dx('seeds', 'stats', 'G'),
				'sort' => 200,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Goals per Game'),
				'internal_name' => 'Goals per Game',
				'abbr' => __dx('seeds', 'stats', 'GPG'),
				'sort' => 300,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 210,
				'class' => 'stat_game',
				'type' => 'entered',
				'validation' => 'team_score_two',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Assists'),
				'internal_name' => 'Assists',
				'abbr' => __dx('seeds', 'stats', 'A'),
				'sort' => 210,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Assists',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Assists per Game'),
				'internal_name' => 'Assists per Game',
				'abbr' => __dx('seeds', 'stats', 'APG'),
				'sort' => 310,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Assists',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 220,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Points'),
				'internal_name' => 'Points',
				'abbr' => __dx('seeds', 'stats', 'P'),
				'sort' => 220,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Points per Game'),
				'internal_name' => 'Points per Game',
				'abbr' => __dx('seeds', 'stats', 'PPG'),
				'sort' => 320,
				'class' => 'stat_per_game',
				'type' => 'season_avg',
				'base' => 'Points',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Game Winning Goals'),
				'internal_name' => 'Game Winning Goals',
				'abbr' => __dx('seeds', 'stats', 'GWG'),
				'sort' => 230,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Game Winning Goals'),
				'internal_name' => 'Game Winning Goals',
				'abbr' => __dx('seeds', 'stats', 'GWG'),
				'sort' => 230,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Game Winning Goals',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Shots'),
				'internal_name' => 'Shots',
				'abbr' => __dx('seeds', 'stats', 'S'),
				'sort' => 240,
				'class' => 'stat_game',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Shots'),
				'internal_name' => 'Shots',
				'abbr' => __dx('seeds', 'stats', 'S'),
				'sort' => 240,
				'class' => 'stat_total',
				'type' => 'season_total',
				'base' => 'Shots',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Shooting Percentage'),
				'internal_name' => 'Shooting Percentage',
				'abbr' => __dx('seeds', 'stats', 'S%'),
				'sort' => 250,
				'class' => 'stat_game',
				'type' => 'game_calc',
				'handler' => 'shot_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'positions' => '!goalkeeper',
				'name' => __d('seeds', 'Shooting Percentage'),
				'internal_name' => 'Shooting Percentage',
				'abbr' => __dx('seeds', 'stats', 'S%'),
				'sort' => 250,
				'class' => 'stat_total',
				'type' => 'season_calc',
				'handler' => 'shot_percent',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 400,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 410,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 410,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 420,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 420,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Shutouts'),
				'internal_name' => 'Shutouts',
				'abbr' => __dx('seeds', 'stats', 'SO'),
				'sort' => 430,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Shutouts'),
				'internal_name' => 'Shutouts',
				'abbr' => __dx('seeds', 'stats', 'SO'),
				'sort' => 430,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shutouts',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Goals Against'),
				'internal_name' => 'Goals Against',
				'abbr' => __dx('seeds', 'stats', 'GA'),
				'sort' => 440,
				'class' => 'stat_games',
				'type' => 'entered',
				'validation' => 'opponent_score',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Goals Against'),
				'internal_name' => 'Goals Against',
				'abbr' => __dx('seeds', 'stats', 'GA'),
				'sort' => 440,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Goals Against',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Shots Against'),
				'internal_name' => 'Shots Against',
				'abbr' => __dx('seeds', 'stats', 'SA'),
				'sort' => 450,
				'class' => 'stat_games',
				'type' => 'entered',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Shots Against'),
				'internal_name' => 'Shots Against',
				'abbr' => __dx('seeds', 'stats', 'SA'),
				'sort' => 450,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Shots Against',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Save Percentage'),
				'internal_name' => 'Save Percentage',
				'abbr' => __dx('seeds', 'stats', 'SV%'),
				'sort' => 460,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'save_percent',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Save Percentage'),
				'internal_name' => 'Save Percentage',
				'abbr' => __dx('seeds', 'stats', 'SV%'),
				'sort' => 460,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'save_percent',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'soccer',
				'positions' => 'goalkeeper',
				'name' => __d('seeds', 'Goals Against Average'),
				'internal_name' => 'Goals Against Average',
				'abbr' => __dx('seeds', 'stats', 'GAA'),
				'sort' => 470,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'gaa',
			],

			/**
			 * Volleyball stats
			 */

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Games Played'),
				'internal_name' => 'Games Played',
				'abbr' => __dx('seeds', 'stats', 'GP'),
				'sort' => 10,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'games',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'wins',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Wins'),
				'internal_name' => 'Wins',
				'abbr' => __dx('seeds', 'stats', 'W'),
				'sort' => 20,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Wins',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'losses',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Losses'),
				'internal_name' => 'Losses',
				'abbr' => __dx('seeds', 'stats', 'L'),
				'sort' => 30,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Losses',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'game_calc',
				'handler' => 'ties',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Ties'),
				'internal_name' => 'Ties',
				'abbr' => __dx('seeds', 'stats', 'T'),
				'sort' => 40,
				'class' => 'stat_games',
				'type' => 'season_total',
				'base' => 'Ties',
				'sum_function' => 'null_sum',
			],

			[
				'sport' => 'volleyball',
				'name' => __d('seeds', 'Win Percent'),
				'internal_name' => 'Win Percent',
				'abbr' => __dx('seeds', 'stats', 'W%'),
				'sort' => 50,
				'class' => 'stat_games',
				'type' => 'season_calc',
				'handler' => 'wins',
			],
		];
	}

	/**
	 * Run Method.
	 *
	 * @return void
	 */
	public function run() {
		$table = $this->table('stat_types');
		$table->insert($this->data())->save();
	}
}
